
package view;

import interfac.Att;
import classes.PlayGround;

/**
 *
 * @author Bruno Henrique <bhenriquecg@gmail.com>
 * <161080391>
 */
public class TelaAddPlayGround extends javax.swing.JFrame implements Att{
    int valor,valortc,valorpt,valorr,valorar,valorcc,valoraa,valores,valorak,valort;
    /**
     * Creates new form TelaAddPlayGround
     */
    public TelaAddPlayGround() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        tirolesa = new javax.swing.JRadioButton();
        arvorismo = new javax.swing.JRadioButton();
        akids = new javax.swing.JRadioButton();
        rapel = new javax.swing.JRadioButton();
        espeleo = new javax.swing.JRadioButton();
        passeiot = new javax.swing.JRadioButton();
        cec = new javax.swing.JRadioButton();
        tec = new javax.swing.JRadioButton();
        atva = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jSpinnert = new javax.swing.JSpinner();
        jSpinnerar = new javax.swing.JSpinner();
        jSpinnerak = new javax.swing.JSpinner();
        jSpinnerr = new javax.swing.JSpinner();
        jSpinneres = new javax.swing.JSpinner();
        jSpinnercc = new javax.swing.JSpinner();
        jSpinnertc = new javax.swing.JSpinner();
        jSpinneraa = new javax.swing.JSpinner();
        jSpinnerpt = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btok = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        valortotal = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PlayGround");
        setPreferredSize(new java.awt.Dimension(1003, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("play ground");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 220, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1000, 50);

        tirolesa.setText("Tirolesa");
        tirolesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tirolesaItemStateChanged(evt);
            }
        });

        arvorismo.setText("Arvorismo");
        arvorismo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                arvorismoItemStateChanged(evt);
            }
        });

        akids.setText("Aventura Kids");
        akids.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                akidsItemStateChanged(evt);
            }
        });

        rapel.setText("Rapel");
        rapel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rapelItemStateChanged(evt);
            }
        });

        espeleo.setText("Espeleo");
        espeleo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                espeleoItemStateChanged(evt);
            }
        });

        passeiot.setText("Passeio de Trator");
        passeiot.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                passeiotItemStateChanged(evt);
            }
        });

        cec.setText("Calvagaria e Charrete ");
        cec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cecItemStateChanged(evt);
            }
        });

        tec.setText("Trilhas e Caminhadas");
        tec.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tecItemStateChanged(evt);
            }
        });

        atva.setText("Atividades Aquáticas ");
        atva.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                atvaItemStateChanged(evt);
            }
        });

        jButton1.setText("Info");
        jButton1.setToolTipText("São 150 metros de percurso com 12 obstáculos com graus de dificuldades distintos.  ");

        jButton2.setText("Info");
        jButton2.setToolTipText("Atividade destinada a crianças, em que é necessário passar por nove obstáculos para chegar até o final e o retorno ao ponto de partida se dá por meio da Tirolesa dos Sonhos  ");

        jButton3.setText("Info");
        jButton3.setToolTipText("Nessa atividade você desce 25m por um trecho da montanha com caminhos de madeira, terra e pedras. O trecho é todo em positivo, ou seja, seus pés estarão sempre apoiados por toda a descida. A verdadeira sensação de andar pelas paredes.\n\n");

        jButton4.setText("Info");
        jButton4.setToolTipText("O espeleoturismo é uma atividade de turismo de aventura que explora cavernas, grutas, lapas (lages ou pedras que formam abrigos), em caráter recreativo, com finalidade turística. ");

        jButton5.setText("Info");
        jButton5.setToolTipText("Com 1km de extensão e 140m de altura. A Tirolesa Voadora TEM 1Km de extensão. Você vai sentir a sensação de estar voando.");

        jButton6.setText("Info");
        jButton6.setToolTipText("De duas formas você pode degustar essa experiência, uma é no passeio externo que leva você a conhecer a rara beleza da região. \nOutra alternativa é o passeio pela fazenda.  ");

        jButton7.setText("Info");
        jButton7.setToolTipText("Oferecemos diversas atividades aquáticas como boia croos, rafting e pescaria\n");

        jButton8.setText("Info");
        jButton8.setToolTipText("Hotel Confort Premium Campina oferece 6 km de trilhas entre a mata nativa, rio, riachos e cachoeiras.\n\n");

        jButton9.setText("Info");
        jButton9.setToolTipText("O passeio pela fazenda passa por locais com paisagens de tirar o fôlego, onde você vai interagir com a natureza e com os animais.\n\n");

        jSpinnert.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnert.setEnabled(false);
        jSpinnert.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnertStateChanged(evt);
            }
        });

        jSpinnerar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerar.setEnabled(false);
        jSpinnerar.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerarStateChanged(evt);
            }
        });

        jSpinnerak.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerak.setEnabled(false);
        jSpinnerak.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerakStateChanged(evt);
            }
        });

        jSpinnerr.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerr.setEnabled(false);
        jSpinnerr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerrStateChanged(evt);
            }
        });

        jSpinneres.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinneres.setEnabled(false);
        jSpinneres.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinneresStateChanged(evt);
            }
        });

        jSpinnercc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnercc.setEnabled(false);
        jSpinnercc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerccStateChanged(evt);
            }
        });

        jSpinnertc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnertc.setEnabled(false);
        jSpinnertc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnertcStateChanged(evt);
            }
        });

        jSpinneraa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinneraa.setEnabled(false);
        jSpinneraa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinneraaStateChanged(evt);
            }
        });

        jSpinnerpt.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jSpinnerpt.setEnabled(false);
        jSpinnerpt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerptStateChanged(evt);
            }
        });

        jLabel2.setText("Quant. Pessoas");

        jLabel3.setText("Quant. Pessoas");

        btok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok-icon.png"))); // NOI18N
        btok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btokActionPerformed(evt);
            }
        });

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor total"));

        valortotal.setBackground(new java.awt.Color(240, 240, 240));
        valortotal.setText("0.00");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(valortotal, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(btok, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btok)
                    .addComponent(jButton10))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(atva)
                    .addComponent(akids)
                    .addComponent(espeleo)
                    .addComponent(tirolesa)
                    .addComponent(cec))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinneres)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jSpinneraa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnert, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerak, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton3)
                                                .addGap(18, 18, 18)
                                                .addComponent(rapel))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jButton6)
                                                .addGap(18, 18, 18)
                                                .addComponent(passeiot)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jSpinnerr, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jSpinnerpt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(arvorismo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jSpinnerar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(58, 58, 58))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(tec)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnertc, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                .addGap(60, 60, 60))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSpinnercc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(194, 194, 194)
                .addComponent(jLabel3)
                .addGap(85, 85, 85))
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(tirolesa)
                    .addComponent(jSpinnert, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(arvorismo)
                    .addComponent(jSpinnerar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(akids)
                    .addComponent(jSpinnerak, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(rapel)
                    .addComponent(jSpinnerr, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton4)
                        .addComponent(espeleo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinneres, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6)
                            .addComponent(passeiot)
                            .addComponent(jSpinnerpt, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSpinnertc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(atva)
                            .addComponent(jButton8)
                            .addComponent(tec)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jSpinneraa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(cec)
                    .addComponent(jSpinnercc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDesktopPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jDesktopPane1);
        jDesktopPane1.setBounds(0, 86, 660, 616);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabela de preços"));

        jLabel4.setText("Tirolesa");

        jLabel5.setText("Aventura Kids");

        jLabel6.setText("Espeleo");

        jLabel7.setText("Atividades Aquáticas");

        jLabel8.setText("Calvagaria e Charrete");

        jLabel9.setText("Arvorismo");

        jLabel10.setText("Rapel");

        jLabel11.setText("Passeio de Trator");

        jLabel12.setText("Trilhas e Caminhadas");

        jLabel13.setText("R$ 35,00");

        jLabel14.setText("R$ 45,00");

        jLabel15.setText("R$ 90,00");

        jLabel16.setText("R$ 50,00");

        jLabel17.setText("R$ 40,00");

        jLabel18.setText("R$ 30,00");

        jLabel19.setText("R$ 80,00");

        jLabel20.setText("R$ 20,00");

        jLabel21.setText("R$ 40,00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addGap(42, 42, 42))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel21))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(680, 100, 300, 420);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btokActionPerformed
       PlayGround pg = new PlayGround();
       TelaCadastro tc = new TelaCadastro();
       pg.setValorpg(valor);
       tc.PlayGround(pg);       
        this.dispose();
    }//GEN-LAST:event_btokActionPerformed

    private void tirolesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tirolesaItemStateChanged
        if (tirolesa.isSelected()) {
            jSpinnert.setEnabled(true);
        }else{
            jSpinnert.setEnabled(false);
            valort=0;atualizar();
        }
    }//GEN-LAST:event_tirolesaItemStateChanged

    private void arvorismoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_arvorismoItemStateChanged
        if (arvorismo.isSelected()) {
            jSpinnerar.setEnabled(true);
        }else{
           jSpinnerar.setEnabled(false);
           valorar=0;atualizar();
        }
    }//GEN-LAST:event_arvorismoItemStateChanged

    private void akidsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_akidsItemStateChanged
        if (akids.isSelected()) {
           jSpinnerak.setEnabled(true);
        }else{
            jSpinnerak.setEnabled(false);
            valorak=0;atualizar();
        }
    }//GEN-LAST:event_akidsItemStateChanged

    private void rapelItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rapelItemStateChanged
        if (rapel.isSelected()) {
            jSpinnerr.setEnabled(true);
        }else{
            jSpinnerr.setEnabled(false);
            valorr=0;atualizar();
        }
    }//GEN-LAST:event_rapelItemStateChanged

    private void espeleoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_espeleoItemStateChanged
        if (espeleo.isSelected()) {
            jSpinneres.setEnabled(true);
        }else{
           jSpinneres.setEnabled(false);
           valores=0;atualizar();
        }
    }//GEN-LAST:event_espeleoItemStateChanged

    private void passeiotItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_passeiotItemStateChanged
        if (passeiot.isSelected()) {
            jSpinnerpt.setEnabled(true);
        }else{
           jSpinnerpt.setEnabled(false);
           valorpt=0;atualizar();
        }
    }//GEN-LAST:event_passeiotItemStateChanged

    private void atvaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_atvaItemStateChanged
        if (atva.isSelected()) {
            jSpinneraa.setEnabled(true);
        }else{
            jSpinneraa.setEnabled(false);
            valoraa=0;
 atualizar();
        }
    }//GEN-LAST:event_atvaItemStateChanged

    private void jSpinnertStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnertStateChanged
          int x =(int) jSpinnert.getValue();
         valort= 35*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnertStateChanged

    private void jSpinnerakStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerakStateChanged
          int x =(int) jSpinnerak.getValue();
         valorak= 45*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnerakStateChanged

    private void jSpinneresStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinneresStateChanged
          int x =(int) jSpinneres.getValue();
         valores= 90*x; 
        atualizar();
    }//GEN-LAST:event_jSpinneresStateChanged

    private void jSpinneraaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinneraaStateChanged
          int x =(int) jSpinneraa.getValue();
         valoraa= 50*x; 
        atualizar();
    }//GEN-LAST:event_jSpinneraaStateChanged

    private void jSpinnerccStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerccStateChanged
          int x =(int) jSpinnercc.getValue();
         valorcc+= 40*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnerccStateChanged

    private void jSpinnerarStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerarStateChanged
          int x =(int) jSpinnerar.getValue();
         valorar= 30*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnerarStateChanged

    private void jSpinnerrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerrStateChanged
        int x =(int) jSpinnerr.getValue();
         valorr= 80*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnerrStateChanged

    private void jSpinnerptStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerptStateChanged
        int x =(int) jSpinnerpt.getValue();
         valorpt= 20*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnerptStateChanged

    private void jSpinnertcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnertcStateChanged
        int x =(int) jSpinnertc.getValue();
         valortc= 40*x; 
        atualizar();
    }//GEN-LAST:event_jSpinnertcStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void tecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tecItemStateChanged
  if (tec.isSelected()) {
            jSpinnertc.setEnabled(true);
        }else{
            jSpinnertc.setEnabled(false);
            valoraa=0;
 atualizar();
        }    }//GEN-LAST:event_tecItemStateChanged

    private void cecItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cecItemStateChanged
  if (cec.isSelected()) {
            jSpinnercc.setEnabled(true);
        }else{
            jSpinnercc.setEnabled(false);
            valoraa=0;
 atualizar();
        }    }//GEN-LAST:event_cecItemStateChanged
public void atualizar() {
       valor = valortc+valorpt+valorr+valorar+valorcc+valoraa+valores+valorak+valort;
        valortotal.setText(String.valueOf(valor));

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton akids;
    private javax.swing.JRadioButton arvorismo;
    private javax.swing.JRadioButton atva;
    private javax.swing.JButton btok;
    private javax.swing.JRadioButton cec;
    private javax.swing.JRadioButton espeleo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSpinner jSpinneraa;
    private javax.swing.JSpinner jSpinnerak;
    private javax.swing.JSpinner jSpinnerar;
    private javax.swing.JSpinner jSpinnercc;
    private javax.swing.JSpinner jSpinneres;
    private javax.swing.JSpinner jSpinnerpt;
    private javax.swing.JSpinner jSpinnerr;
    private javax.swing.JSpinner jSpinnert;
    private javax.swing.JSpinner jSpinnertc;
    private javax.swing.JRadioButton passeiot;
    private javax.swing.JRadioButton rapel;
    private javax.swing.JRadioButton tec;
    private javax.swing.JRadioButton tirolesa;
    private javax.swing.JFormattedTextField valortotal;
    // End of variables declaration//GEN-END:variables
}
