/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import interfac.Att;
import classes.LaCarte;

/**
 *
 * @author Bruno Henrique <bhenriquecg@gmail.com>
 * <161080391>
 */
public class TelaALaCarte extends javax.swing.JFrame implements Att {
    double valor,valord,valortfc,valorm,valorddm,valorcdsnn,valorrdc,valorbr,valorbdd,valorbamm,valorfam,valorf,valorpdpc;
    /**
     * Creates new form TelaALaCarte
     */
    public TelaALaCarte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        dobra = new javax.swing.JCheckBox();
        torta = new javax.swing.JCheckBox();
        milanesa = new javax.swing.JCheckBox();
        file = new javax.swing.JCheckBox();
        dlc = new javax.swing.JCheckBox();
        feijoada = new javax.swing.JCheckBox();
        nata = new javax.swing.JCheckBox();
        bife = new javax.swing.JCheckBox();
        mu = new javax.swing.JCheckBox();
        baiao = new javax.swing.JCheckBox();
        camarao = new javax.swing.JCheckBox();
        batata = new javax.swing.JCheckBox();
        picanha = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        sdobradinha = new javax.swing.JSpinner();
        storta = new javax.swing.JSpinner();
        smuqueca = new javax.swing.JSpinner();
        sdlc = new javax.swing.JSpinner();
        snata = new javax.swing.JSpinner();
        srisoto = new javax.swing.JSpinner();
        sbatata = new javax.swing.JSpinner();
        sbaiao = new javax.swing.JSpinner();
        sbife = new javax.swing.JSpinner();
        sfile = new javax.swing.JSpinner();
        sfeijoada = new javax.swing.JSpinner();
        smilanesa = new javax.swing.JSpinner();
        sporco = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        valortotal1 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("À la carte");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("A La Carte");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 10, 140, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        dobra.setText("Dobradinha                                                                                    ");
        dobra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dobraItemStateChanged(evt);
            }
        });

        torta.setText("Torta de frango com catupiry                                                              ");
        torta.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tortaItemStateChanged(evt);
            }
        });

        milanesa.setText("Filé à milanesa                                                                                           ");
        milanesa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                milanesaItemStateChanged(evt);
            }
        });

        file.setText("Filé à parmegiana                                                                                         ");
        file.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                fileItemStateChanged(evt);
            }
        });

        dlc.setText("Delicia de macaxeira                                                                                 ");
        dlc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                dlcItemStateChanged(evt);
            }
        });

        feijoada.setText("Feijoada                                                                                                       ");
        feijoada.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                feijoadaItemStateChanged(evt);
            }
        });

        nata.setText("Carne de sol na nata                                                                                ");
        nata.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nataItemStateChanged(evt);
            }
        });

        bife.setText("Bife ao molho madeira                                                                              ");
        bife.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bifeItemStateChanged(evt);
            }
        });

        mu.setText("Muqueca                                                                                                 ");
        mu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                muItemStateChanged(evt);
            }
        });

        baiao.setText("Baião de dois                                                                                                  ");
        baiao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                baiaoItemStateChanged(evt);
            }
        });

        camarao.setText("Risoto de camarão                                                                                     ");
        camarao.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                camaraoItemStateChanged(evt);
            }
        });

        batata.setText("Batata recheada                                                                 ");
        batata.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                batataItemStateChanged(evt);
            }
        });

        picanha.setText("Picanha de porco grelhada                                                                           ");
        picanha.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                picanhaItemStateChanged(evt);
            }
        });

        jLabel2.setText(" R$ 30.00");

        jLabel3.setText(" R$ 40.00");

        jLabel4.setText(" R$ 60.00");

        jLabel5.setText(" R$ 40.00");

        jLabel6.setText(" R$ 50.00");

        jLabel7.setText(" R$ 70.00");

        jLabel8.setText(" R$ 30.00");

        jLabel9.setText(" R$ 45.00");

        jLabel10.setText(" R$ 35.00");

        jLabel11.setText(" R$ 35.00");

        jLabel12.setText(" R$ 30.00");

        jLabel13.setText(" R$ 40.00");

        jLabel14.setText(" R$ 50.00");

        sdobradinha.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sdobradinha.setEnabled(false);
        sdobradinha.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdobradinhaStateChanged(evt);
            }
        });

        storta.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        storta.setEnabled(false);
        storta.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                stortaStateChanged(evt);
            }
        });

        smuqueca.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        smuqueca.setEnabled(false);
        smuqueca.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smuquecaStateChanged(evt);
            }
        });

        sdlc.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sdlc.setEnabled(false);
        sdlc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sdlcStateChanged(evt);
            }
        });

        snata.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        snata.setEnabled(false);
        snata.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                snataStateChanged(evt);
            }
        });

        srisoto.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        srisoto.setEnabled(false);
        srisoto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                srisotoStateChanged(evt);
            }
        });

        sbatata.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sbatata.setEnabled(false);
        sbatata.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sbatataStateChanged(evt);
            }
        });

        sbaiao.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sbaiao.setEnabled(false);
        sbaiao.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sbaiaoStateChanged(evt);
            }
        });

        sbife.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sbife.setEnabled(false);
        sbife.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sbifeStateChanged(evt);
            }
        });

        sfile.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sfile.setEnabled(false);
        sfile.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sfileStateChanged(evt);
            }
        });

        sfeijoada.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sfeijoada.setEnabled(false);
        sfeijoada.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sfeijoadaStateChanged(evt);
            }
        });

        smilanesa.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        smilanesa.setEnabled(false);
        smilanesa.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                smilanesaStateChanged(evt);
            }
        });

        sporco.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        sporco.setEnabled(false);
        sporco.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sporcoStateChanged(evt);
            }
        });

        jLabel15.setText("Quant.");

        jLabel16.setText("Valor unid.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(picanha, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(milanesa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(file, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(bife, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(baiao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sporco, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel14)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(mu, javax.swing.GroupLayout.PREFERRED_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(dlc, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(smuqueca)
                                    .addComponent(sdlc)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(dobra, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(batata, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(camarao, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(nata, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                        .addComponent(torta, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(feijoada, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(storta, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                                            .addComponent(snata, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(srisoto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sbatata)
                                            .addComponent(sbaiao, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sbife, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sfile, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(sfeijoada)
                                            .addComponent(smilanesa))
                                        .addComponent(sdobradinha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(64, 64, 64)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel16))
                        .addGap(23, 23, 23))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dobra)
                    .addComponent(jLabel2)
                    .addComponent(sdobradinha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(torta)
                    .addComponent(jLabel3)
                    .addComponent(storta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mu)
                    .addComponent(jLabel4)
                    .addComponent(smuqueca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dlc)
                    .addComponent(jLabel5)
                    .addComponent(sdlc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nata)
                    .addComponent(jLabel6)
                    .addComponent(snata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(camarao)
                    .addComponent(jLabel7)
                    .addComponent(srisoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batata)
                    .addComponent(jLabel8)
                    .addComponent(sbatata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baiao)
                    .addComponent(jLabel9)
                    .addComponent(sbaiao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bife)
                    .addComponent(jLabel10)
                    .addComponent(sbife, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(file)
                    .addComponent(jLabel11)
                    .addComponent(sfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feijoada)
                    .addComponent(jLabel12)
                    .addComponent(sfeijoada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(milanesa)
                    .addComponent(jLabel13)
                    .addComponent(smilanesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(picanha)
                    .addComponent(jLabel14)
                    .addComponent(sporco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Valor total"));

        valortotal1.setBackground(new java.awt.Color(240, 240, 240));
        valortotal1.setText("0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valortotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(209, 209, 209))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(valortotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok-icon.png"))); // NOI18N
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 66, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(ok))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dobraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dobraItemStateChanged
         Dobradinha();
         atualizar();
    }//GEN-LAST:event_dobraItemStateChanged
    public void Dobradinha(){
        if(dobra.isSelected()){
           sdobradinha.setEnabled(true);
        }else{
            sdobradinha.setEnabled(false);
            valord=0;
        }
    }
    private void tortaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tortaItemStateChanged
        Torta();
        atualizar();
    }//GEN-LAST:event_tortaItemStateChanged
    public void Torta(){
        if(torta.isSelected()){
            storta.setEnabled(true);
        }else{
            storta.setEnabled(false);
            valortfc=0;
        }
    }
    private void muItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_muItemStateChanged
        Muqueca();
        atualizar();
    }//GEN-LAST:event_muItemStateChanged
    public void Muqueca(){
        if(mu.isSelected()){
            smuqueca.setEnabled(true);
        }else{
            smuqueca.setEnabled(false);
           valorm=0;
        }
    }
    private void dlcItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_dlcItemStateChanged
        Dlc();
        atualizar();
    }//GEN-LAST:event_dlcItemStateChanged
    public void Dlc(){
        if(dlc.isSelected()){
            sdlc.setEnabled(true);
        }else{
            sdlc.setEnabled(false);
            valorddm=0;
        }
    }
    private void nataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nataItemStateChanged
        Nata();
        atualizar();
    }//GEN-LAST:event_nataItemStateChanged
    public void Nata(){
        if(nata.isSelected()){
            snata.setEnabled(true);
        }else{
           snata.setEnabled(false);
           valorcdsnn=0;
        }
    }
    private void camaraoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_camaraoItemStateChanged
        Camarao();
        atualizar();
    }//GEN-LAST:event_camaraoItemStateChanged
    public void Camarao(){
        if(camarao.isSelected()){
            srisoto.setEnabled(true);
        }else{
            srisoto.setEnabled(false);
            valorrdc=0;
        }
    }
    private void batataItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_batataItemStateChanged
        Batata();
        atualizar();
    }//GEN-LAST:event_batataItemStateChanged
    public void Batata(){
        if(batata.isSelected()){
            sbatata.setEnabled(true);
        }else{
            sbatata.setEnabled(false);
            valorbr=0;
        }
    }
    private void baiaoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_baiaoItemStateChanged
        Baiao();
        atualizar();
    }//GEN-LAST:event_baiaoItemStateChanged
    public void Baiao(){
        if(baiao.isSelected()){
           sbaiao.setEnabled(true);
        }else{
            sbaiao.setEnabled(true);
            valorbdd=0;
        }
    }
    private void bifeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_bifeItemStateChanged
        Bife();
        atualizar();
    }//GEN-LAST:event_bifeItemStateChanged
    public void Bife(){
        if(bife.isSelected()){
            sbife.setEnabled(true);
        }else{
            sbife.setEnabled(false);
            valorbamm=0;
        }
    }
    private void fileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_fileItemStateChanged
        File();
        atualizar();
    }//GEN-LAST:event_fileItemStateChanged
    public void File(){
       if(milanesa.isSelected()){
            sfile.setEnabled(true);
        }else{
            sfile.setEnabled(false);
            valorf=0;
        }
    }
    private void feijoadaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_feijoadaItemStateChanged
        Feijoada();
        atualizar();
    }//GEN-LAST:event_feijoadaItemStateChanged
    public void Feijoada(){
        if(feijoada.isSelected()){
            sfeijoada.setEnabled(true);
        }else{
            sfeijoada.setEnabled(false);
            valorf=0;
        }
    }
    private void milanesaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_milanesaItemStateChanged
        Milanesa();
        atualizar();
    }//GEN-LAST:event_milanesaItemStateChanged
    public void Milanesa(){
        if(milanesa.isSelected()){
            smilanesa.setEnabled(true);
        }else{
            smilanesa.setEnabled(false);
            valorfam=0;
        }
    }
    private void picanhaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_picanhaItemStateChanged
        Picanha();
        atualizar();
    }//GEN-LAST:event_picanhaItemStateChanged

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
        LaCarte lc = new LaCarte();
        TelaEscolhaRestaurante res= new TelaEscolhaRestaurante();
        //String val = valortotal1.getText();
        lc.setValorRefeicao(valor);
        res.LaCarte(lc);
        this.dispose();
    }//GEN-LAST:event_okActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void sdobradinhaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdobradinhaStateChanged
        // TODO add your handling code here:
        int x = (int) sdobradinha.getValue();
        valord = 30*x;
        atualizar();
        
    }//GEN-LAST:event_sdobradinhaStateChanged

    private void stortaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_stortaStateChanged
        // TODO add your handling code here:
        int x = (int) storta.getValue();
        valortfc = 40*x;
        atualizar();
    }//GEN-LAST:event_stortaStateChanged

    private void smuquecaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smuquecaStateChanged
        // TODO add your handling code here:
        int x = (int) smuqueca.getValue();
        valorm = 60*x;
        atualizar();
    }//GEN-LAST:event_smuquecaStateChanged

    private void sdlcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdlcStateChanged
        // TODO add your handling code here:
        int x = (int) sdlc.getValue();
        valorddm = 40*x;
        atualizar();
    }//GEN-LAST:event_sdlcStateChanged

    private void snataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_snataStateChanged
        // TODO add your handling code here:
        int x = (int) snata.getValue();
        valorcdsnn=50*x;
        atualizar();
    }//GEN-LAST:event_snataStateChanged

    private void srisotoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_srisotoStateChanged
        // TODO add your handling code here:
        int x = (int) srisoto.getValue();
        valorrdc = 70*x;
        atualizar();
    }//GEN-LAST:event_srisotoStateChanged

    private void sbatataStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sbatataStateChanged
        // TODO add your handling code here:
        int x = (int) sbatata.getValue();
        valorbr = 30*x;
        atualizar();
    }//GEN-LAST:event_sbatataStateChanged

    private void sbaiaoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sbaiaoStateChanged
        // TODO add your handling code here:
        int x = (int) sbaiao.getValue();
        valorbr = 45*x;
        atualizar();
    }//GEN-LAST:event_sbaiaoStateChanged

    private void sbifeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sbifeStateChanged
        // TODO add your handling code here:
        int x = (int) sbife.getValue();
        valorbdd=35*x;
        atualizar();
    }//GEN-LAST:event_sbifeStateChanged

    private void sfileStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sfileStateChanged
        // TODO add your handling code here:
        int x = (int) sfile.getValue();
        valorbamm=35*x;
        atualizar();
    }//GEN-LAST:event_sfileStateChanged

    private void sfeijoadaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sfeijoadaStateChanged
        // TODO add your handling code here:
        int x = (int) sfeijoada.getValue();
        valorf=30*x;
        atualizar();
    }//GEN-LAST:event_sfeijoadaStateChanged

    private void smilanesaStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_smilanesaStateChanged
        // TODO add your handling code here:
        int x = (int) smilanesa.getValue();
        valorfam=40*x;
        atualizar();
    }//GEN-LAST:event_smilanesaStateChanged

    private void sporcoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sporcoStateChanged
        // TODO add your handling code here:
        int x = (int) sporco.getValue();
        valorpdpc = 50*x;
        atualizar();
    }//GEN-LAST:event_sporcoStateChanged
    public void Picanha(){
        if(picanha.isSelected()){
            sporco.setEnabled(true);
        }else{
            sporco.setEnabled(false);
            valorpdpc = 0;
        }
        
    }
    @Override
     public void atualizar(){
         valor = valord+valortfc+valorm+valorddm+valorcdsnn+valorrdc+valorbr+valorbdd+valorbamm+valorfam+valorf+valorpdpc;
        valortotal1.setText(String.valueOf(valor));
        
           }
  
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox baiao;
    private javax.swing.JCheckBox batata;
    private javax.swing.JCheckBox bife;
    private javax.swing.JCheckBox camarao;
    private javax.swing.JCheckBox dlc;
    private javax.swing.JCheckBox dobra;
    private javax.swing.JCheckBox feijoada;
    private javax.swing.JCheckBox file;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JCheckBox milanesa;
    private javax.swing.JCheckBox mu;
    private javax.swing.JCheckBox nata;
    private javax.swing.JButton ok;
    private javax.swing.JCheckBox picanha;
    private javax.swing.JSpinner sbaiao;
    private javax.swing.JSpinner sbatata;
    private javax.swing.JSpinner sbife;
    private javax.swing.JSpinner sdlc;
    private javax.swing.JSpinner sdobradinha;
    private javax.swing.JSpinner sfeijoada;
    private javax.swing.JSpinner sfile;
    private javax.swing.JSpinner smilanesa;
    private javax.swing.JSpinner smuqueca;
    private javax.swing.JSpinner snata;
    private javax.swing.JSpinner sporco;
    private javax.swing.JSpinner srisoto;
    private javax.swing.JSpinner storta;
    private javax.swing.JCheckBox torta;
    private javax.swing.JFormattedTextField valortotal1;
    // End of variables declaration//GEN-END:variables
}
