package view;

import interfac.Att;
import javax.swing.table.DefaultTableModel;
import classes.Cliente;
import classes.Quarto;

/**
 *
 * @author Bruno Henrique <bhenriquecg@gmail.com>
 * <161080391>
 */
public class TelaAddQuarto extends javax.swing.JFrame implements Att{

    /**
     * Creates new form TelaAddQuarto
     */
    public TelaAddQuarto() {
        initComponents();
        //QuartosDisponiveis();
        preencherTabela();
    }
    String  tipop="", tipols="", tipold="", tipolt="", tipoes="", tipoed="", tipoet="";
    int valor, valorp, valorls, valorld, valorlt, valores, valored, valoret;
    static int contp, contls, contld, contlt, contes, conted, contet,contp1, contls1, contld1, contlt1, contes1, conted1, contet1,camaadd;
    static int y,ls,ld,lt,es,ed,et;
    String tipo = "";
    static int a=5;static int b=15;static int c=20;static int d=5;static int e=15;static int f=20;static int g=5;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        valortotal = new javax.swing.JFormattedTextField();
        btok3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        presidencial = new javax.swing.JCheckBox();
        spinp = new javax.swing.JSpinner();
        luxosimples = new javax.swing.JCheckBox();
        spinls = new javax.swing.JSpinner();
        addls = new javax.swing.JCheckBox();
        luxoduplo = new javax.swing.JCheckBox();
        spinld = new javax.swing.JSpinner();
        addld = new javax.swing.JCheckBox();
        luxotriplo = new javax.swing.JCheckBox();
        executivosimples = new javax.swing.JCheckBox();
        spinlt = new javax.swing.JSpinner();
        addlt = new javax.swing.JCheckBox();
        spines = new javax.swing.JSpinner();
        executivoduplo = new javax.swing.JCheckBox();
        spined = new javax.swing.JSpinner();
        added = new javax.swing.JCheckBox();
        executivotriplo = new javax.swing.JCheckBox();
        spinet = new javax.swing.JSpinner();
        addet = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaquartos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quartos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quartos");
        jLabel1.setVerifyInputWhenFocusTarget(false);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(460, 10, 161, 30);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N
        jLabel2.setText("Valor:");

        valortotal.setBackground(new java.awt.Color(240, 240, 240));
        valortotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        valortotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));
        valortotal.setText(" 0.0");
        valortotal.setFont(new java.awt.Font("Perpetua Titling MT", 1, 24)); // NOI18N

        btok3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok-icon.png"))); // NOI18N
        btok3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btok3ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancelar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        presidencial.setText("Presidencial");
        presidencial.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                presidencialItemStateChanged(evt);
            }
        });

        spinp.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spinp.setEnabled(false);
        spinp.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinpStateChanged(evt);
            }
        });

        luxosimples.setText("Luxo Simples");
        luxosimples.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                luxosimplesStateChanged(evt);
            }
        });

        spinls.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spinls.setEnabled(false);
        spinls.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinlsStateChanged(evt);
            }
        });

        addls.setText("Cama Adicional");
        addls.setEnabled(false);
        addls.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addlsItemStateChanged(evt);
            }
        });

        luxoduplo.setText("Luxo Duplo");
        luxoduplo.setToolTipText("");
        luxoduplo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                luxoduploStateChanged(evt);
            }
        });

        spinld.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        spinld.setEnabled(false);
        spinld.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinldStateChanged(evt);
            }
        });

        addld.setText("Cama Adicional");
        addld.setEnabled(false);
        addld.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addldItemStateChanged(evt);
            }
        });

        luxotriplo.setText("Luxo Triplo");
        luxotriplo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                luxotriploStateChanged(evt);
            }
        });

        executivosimples.setText("Executivo Simples");
        executivosimples.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                executivosimplesStateChanged(evt);
            }
        });

        spinlt.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        spinlt.setEnabled(false);
        spinlt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinltStateChanged(evt);
            }
        });

        addlt.setText("Cama Adicional");
        addlt.setEnabled(false);
        addlt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addltItemStateChanged(evt);
            }
        });

        spines.setModel(new javax.swing.SpinnerNumberModel(0, 0, 5, 1));
        spines.setEnabled(false);
        spines.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinesStateChanged(evt);
            }
        });

        executivoduplo.setText("Executivo Duplo");
        executivoduplo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executivoduploActionPerformed(evt);
            }
        });

        spined.setModel(new javax.swing.SpinnerNumberModel(0, 0, 15, 1));
        spined.setEnabled(false);
        spined.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinedStateChanged(evt);
            }
        });

        added.setText("Cama Adicional");
        added.setEnabled(false);
        added.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addedItemStateChanged(evt);
            }
        });

        executivotriplo.setText("Executivo Triplo");
        executivotriplo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                executivotriploStateChanged(evt);
            }
        });

        spinet.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20, 1));
        spinet.setEnabled(false);
        spinet.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinetStateChanged(evt);
            }
        });

        addet.setText("Cama Adicional");
        addet.setEnabled(false);
        addet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                addetItemStateChanged(evt);
            }
        });

        jButton2.setText("Info");
        jButton2.setToolTipText("Comporta até 4 pessoas em 2 quartos\nseparados e uma sala de jogos e home theater, ideal para famílias em férias.");

        jButton3.setText("Info");
        jButton3.setToolTipText("Comporta 1 pessoa e possui home theater e uma cama adicional*.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Info");
        jButton4.setToolTipText("Comporta 2 pessoas e possui home theater e uma cama adicional*.");

        jButton5.setText("Info");
        jButton5.setToolTipText("Comporta 3 pessoas e possui home theater e uma cama adicional*.");

        jButton6.setText("Info");
        jButton6.setToolTipText("Comporta 1 pessoa.");

        jButton7.setText("Info");
        jButton7.setToolTipText("Comporta 2 pessoas e uma cama adiciona*l.");

        jButton8.setText("Info");
        jButton8.setToolTipText("Comporta 2 pessoas e uma cama adicional*.");

        tabelaquartos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"5", "5", "15", "20", "5", "15", "20"}
            },
            new String [] {
                "Presidencial (R$ 1200)", "Luxo Simples (R$ 520)", "Luxo Duplo (R$ 570)", "Luxo Triplo (R$ 620)", "Executivo Simples (R$ 360)", "Executivo Duplol (R$ 385)", "Executivo Triplo (R$ 440)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaquartos);

        jLabel3.setText("*Cama Adicional R$ 90,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7)
                            .addComponent(jButton8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(presidencial, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spinp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(243, 243, 243)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luxosimples, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spinls, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addls))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luxoduplo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spinld, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addld))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(luxotriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spinlt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addlt))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(executivosimples, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spines, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(executivoduplo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spined, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(added))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(executivotriplo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(spinet, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(addet))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btok3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spinp, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(presidencial)
                        .addComponent(jButton2)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(luxosimples)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spinls, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addls))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(luxoduplo)
                        .addComponent(jButton4))
                    .addComponent(spinld, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addld))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(luxotriplo)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spinlt, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addlt))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(executivosimples)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spines, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(executivoduplo)
                        .addComponent(jButton7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(spined, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(added))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(executivotriplo)
                        .addComponent(jButton8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(spinet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(addet)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(valortotal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btok3)
                    .addComponent(jButton1))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     void preencherTabela() {
        DefaultTableModel model = (DefaultTableModel) tabelaquartos.getModel();
       model.setNumRows(0);//model.addColumn(null,new Object[]{contp,contls,contld,contlt,contes,conted,contet} );
       model.addRow(new Object[]{contp,contls,contld,contlt,contes,conted,contet});
       //model.addColumn(2, new Object[]{contp,contls,contld,contlt,contes,conted,contet});
        }

    
    private void btok3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btok3ActionPerformed
        Quarto q = new Quarto();
        Cliente c = new Cliente();
        TelaCadastro tc = new TelaCadastro();
        q.getEd().setValored(valored);
        q.getEs().setValores(valores);
        q.getEt().setValoret(valoret);
        q.getLd().setValorld(valorld);
        q.getLs().setValorls(valorls);
        q.getLt().setValorlt(valorlt);
        q.getP().setValorp(valorp);
        
        q.getEd().setQuartoz(tipoed);
        q.getEs().setQuartoz(tipoes);
        q.getEt().setQuartoz(tipoet);
        q.getLd().setQuartoz(tipold);
        q.getLs().setQuartoz(tipols);
        q.getLt().setQuartoz(tipolt);
        q.getP().setQuartoz(tipop);
        
        c.setContp(contp1);
        c.setContls(contls1);
        c.setContld(contld1);
        c.setContlt(contlt1);
        c.setContes(contes1);
        c.setConted(conted1);
        c.setContet(contet1);
        //q.setTipo(tipo);
        tc.Quarto(q);
        tc.Cliente(c);
        y+=contp1;
        ls+=contls1;ld+=contld1;lt+=contlt1;
        es+=contes1;ed+=conted1;et+=contet1;
        this.dispose();
    }//GEN-LAST:event_btok3ActionPerformed

    private void luxosimplesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_luxosimplesStateChanged
        if (luxosimples.isSelected()) {
            spinls.setEnabled(true);
            addls.setEnabled(true);
        } else {
            spinls.setEnabled(false);
            addls.setEnabled(false);
            valorls = 0;
        }
    }//GEN-LAST:event_luxosimplesStateChanged

    private void luxotriploStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_luxotriploStateChanged

        if (luxotriplo.isSelected()) {
            spinlt.setEnabled(true);
            addlt.setEnabled(true);
        } else {
            spinlt.setEnabled(false);
            addlt.setEnabled(false);
            valorlt = 0;
        }
    }//GEN-LAST:event_luxotriploStateChanged

    private void executivosimplesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_executivosimplesStateChanged
        if (executivosimples.isSelected()) {
            spines.setEnabled(true);
        } else {
            spines.setEnabled(false);
            valores = 0;
        }
    }//GEN-LAST:event_executivosimplesStateChanged

    private void executivoduploActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executivoduploActionPerformed
        if (executivoduplo.isSelected()) {
            spined.setEnabled(true);
            added.setEnabled(true);
        } else {
            spined.setEnabled(false);
            added.setEnabled(false);
            valored = 0;
        }
    }//GEN-LAST:event_executivoduploActionPerformed

    private void executivotriploStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_executivotriploStateChanged
        if (executivotriplo.isSelected()) {
            spinet.setEnabled(true);
            addet.setEnabled(true);
        } else {
            spinet.setEnabled(false);
            addet.setEnabled(false);
            valoret = 0;
        }
    }//GEN-LAST:event_executivotriploStateChanged

    private void luxoduploStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_luxoduploStateChanged
        if (luxoduplo.isSelected()) {
            spinld.setEnabled(true);
            addld.setEnabled(true);
        } else {
            spinld.setEnabled(false);
            addld.setEnabled(false);
            valorld = 0;
        }
    }//GEN-LAST:event_luxoduploStateChanged

    private void presidencialItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_presidencialItemStateChanged
        if (presidencial.isSelected()) {
            spinp.setEnabled(true);
            atualizar();
        } else {
            spinp.setEnabled(false);
            valorp = 0;
            atualizar();
        }
    }//GEN-LAST:event_presidencialItemStateChanged

    private void spinpStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinpStateChanged
        int x = (int) spinp.getValue();
        valorp = 1200 * x;
        tipop = "Presidencial ";
        contp = g - y - x;
        contp1 = x;
         if (contp < 0) {
            presidencial.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            presidencial.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
        //QuartosDisponiveis();

    }//GEN-LAST:event_spinpStateChanged

    private void spinlsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinlsStateChanged
        int x = (int) spinls.getValue();
        valorls = 520 * x;
        tipols = "Luxo Simples ";
        contls = a - ls - x;
        contls1 = x;
          if (contls < 0) {
            luxosimples.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            luxosimples.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
        //QuartosDisponiveis();
    }//GEN-LAST:event_spinlsStateChanged

    private void spinldStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinldStateChanged
        int x = (int) spinld.getValue();
        valorld = 570 * x;
        tipold = "Luxo Duplo ";
        contld = b - ld - x;
        contld1 = x;
        if (contld < 0) {
            luxoduplo.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            luxoduplo.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
        //QuartosDisponiveis();
    }//GEN-LAST:event_spinldStateChanged

    private void spinltStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinltStateChanged
        int x = (int) spinlt.getValue();
        valorlt = 620 * x;
        tipolt = "Luxo Triplo ";
        contlt = c - lt - x;
        contlt1 = x;
        if (contlt < 0) {
            luxotriplo.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            luxotriplo.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
    }//GEN-LAST:event_spinltStateChanged

    private void spinesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinesStateChanged
        int x = (int) spines.getValue();
        valores = 360 * x;
        tipoes = "Executivo Simples ";
        contes = d - es - x;
        contes1 = x;
         if (contes < 0) {
            executivosimples.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            executivosimples.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
        //QuartosDisponiveis();
    }//GEN-LAST:event_spinesStateChanged

    private void spinedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinedStateChanged
        int x = (int) spined.getValue();
        valored = 385 * x;
        tipoed = "Executivo Duplo ";
        conted = e - ed - x;
        conted1 = x;
         if (conted < 0) {
            executivoduplo.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            executivoduplo.setEnabled(true);
            btok3.setEnabled(true);
         }
        atualizar();
        //QuartosDisponiveis();
    }//GEN-LAST:event_spinedStateChanged

    private void spinetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinetStateChanged
        int x = (int) spinet.getValue();
        valoret = 440 * x;
        tipoet = "Executivo Triplo ";
        contet = f - et - x;
        contet1 = x;
        if (contet < 0) {
            executivotriplo.setEnabled(false);
            btok3.setEnabled(false);
        } else {
            executivotriplo.setEnabled(true);
            btok3.setEnabled(true);
        }
        atualizar();
        //QuartosDisponiveis();
    }//GEN-LAST:event_spinetStateChanged

    private void addlsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addlsItemStateChanged
        if (addls.isSelected()) {
            valorls += 90;tipols += "*Cama Adicional";
        } else {
            valorls -= 90;tipols += "";
        }
        atualizar();
    }//GEN-LAST:event_addlsItemStateChanged

    private void addldItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addldItemStateChanged
        if (addld.isSelected()) {
            valorld += 90;tipold += "*Cama Adicional";
        } else {
            valorld -= 90;tipold += "";
        }
        atualizar();
    }//GEN-LAST:event_addldItemStateChanged

    private void addltItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addltItemStateChanged
        if (addet.isSelected()) {
            valorlt += 90;tipolt += "*Cama Adicional";
        } else {
            valorlt -= 90;tipolt += "";
        }
        atualizar();
    }//GEN-LAST:event_addltItemStateChanged

    private void addedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addedItemStateChanged
        if (addet.isSelected()) {
            valored += 90;tipoed += "*Cama Adicional";
        } else {
            valored -= 90;tipoed += "";
        }
        atualizar();
    }//GEN-LAST:event_addedItemStateChanged

    private void addetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_addetItemStateChanged
        if (addet.isSelected()) {
            valoret += 90;tipoet += "*Cama Adicional"; 
        } else {
            valoret -= 90;tipoet += "";
        }
        atualizar();
    }//GEN-LAST:event_addetItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    @Override
    public void atualizar() {
         preencherTabela();
        //tipo = tipop+tipols+tipold+tipolt+tipoes+tipoed+tipoet;
        valor = valorp + valorls + valorld + valorlt + valores + valored + valoret;
        valortotal.setText(String.valueOf(valor));

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox added;
    private javax.swing.JCheckBox addet;
    private javax.swing.JCheckBox addld;
    private javax.swing.JCheckBox addls;
    private javax.swing.JCheckBox addlt;
    private javax.swing.JButton btok3;
    private javax.swing.JCheckBox executivoduplo;
    private javax.swing.JCheckBox executivosimples;
    private javax.swing.JCheckBox executivotriplo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox luxoduplo;
    private javax.swing.JCheckBox luxosimples;
    private javax.swing.JCheckBox luxotriplo;
    private javax.swing.JCheckBox presidencial;
    private javax.swing.JSpinner spined;
    private javax.swing.JSpinner spines;
    private javax.swing.JSpinner spinet;
    private javax.swing.JSpinner spinld;
    private javax.swing.JSpinner spinls;
    private javax.swing.JSpinner spinlt;
    private javax.swing.JSpinner spinp;
    private javax.swing.JTable tabelaquartos;
    private javax.swing.JFormattedTextField valortotal;
    // End of variables declaration//GEN-END:variables
}
